## Intermediate Machine Learning with Scikit-Lear

## Multiple linear regression/Multilinear regression

In [20]:
import pandas as pd
import seaborn as sns
from  sklearn.linear_model import LinearRegression

import warnings

df = sns.load_dataset('tips')
df.head()
#double column value because it is depends on another column(y)
#select the feature column from dataframe(df)
X_bill = df[['total_bill','size']]
#select the target(label) column from dataframe(df)
y_tip = df['tip']
#Initialize the model
model=LinearRegression()
#trained the model
model.fit(X_bill, y_tip)
#Predict the tip

warnings.filterwarnings("ignore", category=UserWarning)
X_test=[[50,2]]
model.predict(X_test)

array([5.68980717])

In [16]:
#double column value because it is depends on another column(y)
#select the feature column from dataframe(df)
df['smoker_number'] = df['smoker'].map({'Yes':1,'No':0})
df.head()

total_bill   tip     sex smoker  day    time  size smoker_number
0       16.99  1.01  Female     No  Sun  Dinner     2             0
1       10.34  1.66    Male     No  Sun  Dinner     3             0
2       21.01  3.50    Male     No  Sun  Dinner     3             0
3       23.68  3.31    Male     No  Sun  Dinner     2             0
4       24.59  3.61  Female     No  Sun  Dinner     4             0

In [ ]:

X_bill = df[['total_bill','size','smoker_number']]
#select the target(label) column from dataframe(df)
y_tip = df['tip']
#Initialize the model
model=LinearRegression()
#trained the model
model.fit(X_bill, y_tip)
#Predict the tip

warnings.filterwarnings("ignore", category=UserWarning)


array([5.68066557])

In [19]:
X_test=[[50,2,1]]
print(model.predict(X_test))
X_test=[[50,2,0]]
print(model.predict(X_test))

[5.68066557]
[5.76409813]


## Linear 
### Classification

In [21]:
import pandas as pd
import seaborn as sns
from  sklearn.linear_model import LinearRegression

import warnings

df = sns.load_dataset('tips')
df.head()
#double column value because it is depends on another column(y)
#select the feature column from dataframe(df)
X_bill = df[['total_bill','size']]
#select the target(label) column from dataframe(df)
y_tip = df['tip']
#Initialize the model
model=LinearRegression()
#trained the model
model.fit(X_bill, y_tip)
#Predict the tip

warnings.filterwarnings("ignore", category=UserWarning)
X_test=[[50,2]]
model.predict(X_test)

array([5.68980717])

## Classification
## Logistic regression
### Binary Classification

In [24]:
import pandas as pd
import seaborn as sns
from  sklearn.linear_model import LogisticRegression

import warnings

df = sns.load_dataset('tips')
df.head()
#double column value because it is depends on another column(y)
#select the feature column from dataframe(df)
X = df[['total_bill', 'size', 'tip']]
#select the target(label) column from dataframe(df)
y = df['smoker']
#Initialize the model
model=LogisticRegression()
#trained the model
model.fit(X, y)
#Predict the tip

warnings.filterwarnings("ignore", category=UserWarning)
X_test=[[50.527, 2, 5.67]]
# predict
model.predict(X_test)

array(['Yes'], dtype=object)

## GaussianNB Algorithm

In [25]:
import pandas as pd
import seaborn as sns
from  sklearn.naive_bayes import GaussianNB

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

df = sns.load_dataset('tips')
df.head()
#double column value because it is depends on another column(y)
#select the feature column from dataframe(df)
X = df[['total_bill', 'size', 'tip']]
#select the target(label) column from dataframe(df)
y = df['smoker']
#Initialize the model
model=GaussianNB()
#trained the model
model.fit(X, y)
#Predict the tip


X_test=[[50.527, 2, 5.67]]
# predict
model.predict(X_test)

array(['Yes'], dtype='<U3')

## Decision Trees

In [26]:
import pandas as pd
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

df = sns.load_dataset('tips')
df.head()
#double column value because it is depends on another column(y)
#select the feature column from dataframe(df)
X = df[['total_bill', 'size', 'tip']]
#select the target(label) column from dataframe(df)
y = df['smoker']
#Initialize the model
model=DecisionTreeClassifier()
#trained the model
model.fit(X, y)
#Predict the tip 
X_test=[[50.527, 2, 5.67]]
# predict
model.predict(X_test)

array(['Yes'], dtype=object)

## Regression Metrics

In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
# load the data
df = sns.load_dataset('tips')
df.head()

X = df[['total_bill', 'size']]
y = df['tip']

# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

# call the model
model = LinearRegression()

# fit the model
model.fit(X_train, y_train)

# metric to evaluate the model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error
y_pred = model.predict(X_test)

print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")
print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Absolute Percentage Error: {mean_absolute_percentage_error(y_test, y_pred)}")
# root mean squared error
print(f"Root Mean Squared Error: {np.sqrt(mean_squared_error(y_test, y_pred))}")

Mean Squared Error: 0.6485996190543517
R2 Score: 0.4811084097989491
Mean Absolute Error: 0.6639235737596481
Mean Absolute Percentage Error: 0.27978917485910254
Root Mean Squared Error: 0.8053568271607013
